# Generated by Django 5.0 on 2023-12-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_userprofile_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="test1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="test2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="test3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="test4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
